name: prcup_backend
description: prcup_backend

version: '1.0.0'

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  http: ^0.13.5
  googleapis_auth: ^1.3.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3
