name: Compile API

on:
  push:
    branches: main
    # paths: 'backend/api/**

jobs:
  compile-api:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      workdir: ./backend

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        working-directory: ${{ env.workdir }}
        run: dart pub get

      - name: Compile API
        working-directory: ${{ env.workdir }}
        run: dart compile exe ./lib/api/main.dart -o /tmp/prcup-api

      - name: Deploy Executable
        run: |
          echo ${{ secrets.SSH_KEY }} > /tmp/sshkey.pub \
            && scp -i /tmp/sshkey.pub /tmp/prcup-api ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SCP_TARGET }} \
            && ssh -i /tmp/sshkey.pub ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} sh ${{ secrets.SCP_TARGET }}/setup.sh \
            && rm /tmp/sshkey.pub
