name: Worker

on:
  push:
    branches: main

jobs:
  build-web:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies 
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build --dart-define=FIREBASE_URL=${{ secrets.FIREBASE_URL }} --dart-define=FIREBASE_SA_CREDS=${{ secrets.FIREBASE_SA_CREDS }} web

      - name: Deploy to Github Pages
        run: |
          cd build/web
          git config --global user.email waldeck-dev
          git config --global user.name prcup
          git init
          git add --all
          git commit -m "Deploy"
          git push -f https://waldeck-dev:${{ secrets.GH_TOKEN }}@github.com/waldeck-dev/prcup.git master:gh-pages
