name: Hosting

on:
  push:
    branches: main
    paths: 'flutter/**'

jobs:
  build-web:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      workdir: ./flutter

    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy executable
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          first_ssh: sh ${{ secrets.SCP_TARGET }}/hosting.sh
